name: Deploy Python Backend to Railway

on:
  push:
    branches: [ main ]
    paths: 
      - 'python-backend/**'
      - '.github/workflows/deploy-python-backend.yml'
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Railway CLI
      run: |
        curl -fsSL https://railway.app/install.sh | sh
        echo "$HOME/.railway/bin" >> $GITHUB_PATH
        
    - name: Deploy to Railway
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        cd python-backend
        railway login --token $RAILWAY_TOKEN
        railway up --detach
        
    - name: Get Railway URL
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        cd python-backend
        RAILWAY_URL=$(railway status --json | jq -r '.deployments[0].url // "No URL available"')
        echo "🚀 Python backend deployed to: $RAILWAY_URL"
        echo "RAILWAY_URL=$RAILWAY_URL" >> $GITHUB_ENV
        
    - name: Health Check
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        cd python-backend
        sleep 30  # Wait for deployment
        RAILWAY_URL=$(railway status --json | jq -r '.deployments[0].url // ""')
        if [ ! -z "$RAILWAY_URL" ]; then
          echo "Testing health check at: $RAILWAY_URL"
          curl -f "$RAILWAY_URL" || echo "Health check failed, but deployment may still be starting"
        fi
        
    - name: Update Supabase Edge Function (Optional)
      if: success()
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      run: |
        # This step requires Supabase CLI and access token
        # Uncomment and configure if you want automatic Supabase updates
        # cd python-backend
        # RAILWAY_URL=$(railway status --json | jq -r '.deployments[0].url // ""')
        # if [ ! -z "$RAILWAY_URL" ]; then
        #   echo "Would update Supabase Edge Function with: $RAILWAY_URL"
        #   # supabase secrets set PYTHON_BACKEND_URL="$RAILWAY_URL" --project-ref kfikvadshmptpwscgbyu
        # fi

    - name: Notify Success
      if: success()
      run: |
        echo "✅ Deployment successful!"
        echo "🐍 Python backend is now running on Railway"
        echo "🔗 Check your Railway dashboard for the live URL"
        
    - name: Notify Failure
      if: failure()
      run: |
        echo "❌ Deployment failed!"
        echo "Check the logs above for details"