name: Lint and Format Check

permissions:
  contents: read
  issues: write
  pull-requests: write

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'frontend/**'
      - 'supabase-backend/**'
      - 'python-backend/**'
      - '.github/workflows/lint-pr.yml'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Debug - Verify checkout
        run: |
          echo "=== Current directory ==="
          pwd
          ls -la
          echo "=== Frontend directory ==="
          if [ -d "frontend" ]; then
            ls -la frontend/
            echo "Frontend package.json exists: $([ -f "frontend/package.json" ] && echo "YES" || echo "NO")"
            echo "Frontend package-lock.json exists: $([ -f "frontend/package-lock.json" ] && echo "YES" || echo "NO")"
          else
            echo "Frontend directory does not exist!"
          fi
          echo "=== Supabase-backend directory ==="
          if [ -d "supabase-backend" ]; then
            ls -la supabase-backend/
            echo "Supabase-backend package.json exists: $([ -f "supabase-backend/package.json" ] && echo "YES" || echo "NO")"
            echo "Supabase-backend package-lock.json exists: $([ -f "supabase-backend/package-lock.json" ] && echo "YES" || echo "NO")"
          else
            echo "Supabase-backend directory does not exist!"
          fi
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            supabase-backend/package-lock.json
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.ts
            **/*.tsx
            **/*.js
            **/*.jsx
            **/*.py
      
      - name: Install frontend dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if [ -d "./frontend" ] && [ -f "./frontend/package.json" ]; then
            echo "Frontend directory found with package.json"
            cd ./frontend
            echo "Attempting npm ci..."
            if [ -f "package-lock.json" ]; then
              npm ci
            else
              echo "No package-lock.json found, falling back to npm install"
              npm install
            fi
            echo "Verifying eslint-config-next is installed..."
            npm list eslint-config-next || echo "eslint-config-next not found in dependencies"
          else
            echo "Cannot install frontend dependencies - no package.json found"
            ls -la ./frontend/ || echo "Frontend directory does not exist"
            exit 1
          fi
      
      - name: Install backend dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          if [ -d "./supabase-backend" ] && [ -f "./supabase-backend/package-lock.json" ]; then
            echo "Supabase-backend directory and package-lock.json found"
            cd ./supabase-backend
            echo "Attempting npm ci..."
            if ! npm ci; then
              echo "npm ci failed, trying npm install as fallback..."
              npm install
            fi
          else
            echo "Supabase-backend directory or package-lock.json not found, attempting npm install"
            if [ -d "./supabase-backend" ] && [ -f "./supabase-backend/package.json" ]; then
              cd ./supabase-backend && npm install
            else
              echo "Cannot install supabase-backend dependencies - no package.json found"
              exit 1
            fi
          fi
      
      - name: Verify ESLint configuration
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./frontend
        run: |
          echo "Verifying ESLint configuration..."
          npx eslint --version
          echo "Checking if eslint-config-next is available..."
          if npx eslint --print-config lib/supabase.ts > /dev/null 2>&1; then
            echo "✅ ESLint configuration is valid"
          else
            echo "❌ ESLint configuration failed"
            echo "Attempting to reinstall dependencies..."
            npm install
            if npx eslint --print-config lib/supabase.ts > /dev/null 2>&1; then
              echo "✅ ESLint configuration is now valid after reinstall"
            else
              echo "❌ ESLint configuration still failing"
              exit 1
            fi
          fi
      
      - name: Install prettier
        if: steps.changed-files.outputs.any_changed == 'true'
        run: npm install -g prettier@3
      
      - name: Check formatting with Prettier
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "Checking formatting for changed files..."
          echo "All changed files: ${{ steps.changed-files.outputs.all_changed_files }}"
          
          # Filter files to only include formats Prettier can handle
          PRETTIER_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep -E '\.(ts|tsx|js|jsx|json|css|scss|md|yaml|yml)$' | tr '\n' ' ')
          
          if [ -n "$PRETTIER_FILES" ]; then
            echo "Files to check with Prettier: $PRETTIER_FILES"
            prettier --check $PRETTIER_FILES
          else
            echo "No files found that Prettier can format"
          fi
      
      - name: Lint frontend files
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./frontend
        run: |
          FRONTEND_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep '^frontend/' | sed 's|^frontend/||' | tr '\n' ' ')
          if [ -n "$FRONTEND_FILES" ]; then
            echo "Linting frontend files: $FRONTEND_FILES"
            npx eslint $FRONTEND_FILES
          else
            echo "No frontend files to lint"
          fi
      
      - name: Lint supabase-backend files
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./supabase-backend
        run: |
          BACKEND_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep '^supabase-backend/' | sed 's|^supabase-backend/||' | tr '\n' ' ')
          if [ -n "$BACKEND_FILES" ]; then
            echo "Supabase backend files changed: $BACKEND_FILES"
            echo "Supabase backend linting will be added once eslint is configured"
          else
            echo "No supabase backend files to lint"
          fi
      
      - name: Setup Python
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install Python dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./python-backend
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Check Python code formatting with Black
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./python-backend
        run: |
          PYTHON_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep '^python-backend/.*\.py$' | tr '\n' ' ')
          if [ -n "$PYTHON_FILES" ]; then
            echo "Checking Python formatting: $PYTHON_FILES"
            black --check --diff $PYTHON_FILES
          else
            echo "No Python files to check formatting"
          fi
      
      - name: Lint Python files with flake8
        if: steps.changed-files.outputs.any_changed == 'true'
        working-directory: ./python-backend
        run: |
          PYTHON_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n' | grep '^python-backend/.*\.py$' | tr '\n' ' ')
          if [ -n "$PYTHON_FILES" ]; then
            echo "Linting Python files: $PYTHON_FILES"
            flake8 $PYTHON_FILES
          else
            echo "No Python files to lint"
          fi
      
      - name: Comment on PR
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Linting or formatting checks failed. Please run `npm run lint` and `prettier --write` on your changed files.'
            })

